config/routes.rb
Rails.application.routes.draw do
  root 'quizs#index'
  resources :quizs
  get 'get_image/:id', to: 'quizs#get_image'
  post 'quizs/search', to: 'quizs#search'
  post 'quizs/:id', to: 'quizs#answer'
  resources :users
  get 'top/main'
  post 'top/login'
  get 'top/logout'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/question.rb
class Question < ApplicationRecord
    validates :title, presence: true
    validates :question, presence: true
    validates :answer, presence: true
    validates :comment, presence: true
end

app/models/user.rb
class User < ApplicationRecord
    validates :uid, uniqueness: true, presence: true
    validates :pass, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :null_session
end

app/controllers/quizs_controller.rb
class QuizsController < ApplicationController
  
  
  
  
  def index
    @quizs = Question.page(params[:page]).per(5).order(:id)
  end
  
  def new
    @quiz = Question.new
  end

  def create
    if params[:question][:file] == nil
      file = []
    else
      file = params[:question][:file].read
    end
    @quiz = Question.new(title: params[:question][:title],
    question: params[:question][:question],
    img: file,
    answer: params[:question][:answer],
    comment: params[:question][:comment]
    )
    if @quiz.save
      flash[:notice] = "投稿しました"
      redirect_to '/'
    else
      render 'new'
    end
  end
  
  def get_image
    image = Question.find(params[:id])
    send_data image.img, disposition: :inline, type: 'image/png'
  end
  
  def show
    @quiz = Question.find(params[:id])
  end
  
  def search
    @keyword = params[:keyword]
    @quizs = Question.where('title LIKE ? OR question LIKE ?', '%'+params[:keyword]+'%', '%'+params[:keyword]+'%')
    render 'index'
  end
  
  def answer
    @quiz = Question.find(params[:id])
    @ans = params[:pans]
    if @ans == @quiz.answer
      flash.now[:notice] = "正解です"
    else
      flash.now[:notice] = "不正解です"
    end
  end
  
  def destroy
    quiz = Question.find(params[:id])
    quiz.destroy
    flash[:notice] = "ツイートを削除しました"
    redirect_to quizs_path
  end

  

  
end

app/controllers/top_controller.rb
class TopController < ApplicationController
    def main
        render 'login'
    end

    def login
        user = User.find_by(uid: params[:uid])
        if user and BCrypt::Password.new(user.pass) == params[:pass]
            flash[:notice] = 'ログインしました'
            session[:login_uid] = user.uid
            redirect_to root_path
        else
            flash[:notice] = 'ログインに失敗しました'
            render 'login'
        end
    end

    def logout
        flash[:notice] = 'ログアウトしました'
        session.delete(:login_uid)
        redirect_to root_path
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
    
    def index
        @users = User.all
    end

    def new
        @user = User.new
    end

    def create 
        @user = User.new(uid: params[:user][:uid],pass: params[:user][:pass])
        if @user.valid?
            @user.pass = BCrypt::Password.create(params[:user][:pass])
            @user.save
            flash[:notice] = '新規登録しました'
        redirect_to users_path
        else
            render 'new'
        end
    end

    def destroy
        user = User.find(params[:id])
        user.destroy
        flash[:notice] = '登録情報を削除しました'
        redirect_to users_path
    end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/jobs/application_job.rb
class ApplicationJob < ActiveJob::Base
end

app/helpers/quizs_helper.rb
module QuizsHelper
end

app/helpers/top_helper.rb
module TopHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Quiz</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.9.0/css/all.css">
  
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%# <script src="http://ajax.googleapis.com/ajax/libs/jquery/1.9.1/jquery.min.js"></script> %>
    <%= javascript_tag 'application', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    
    
    
  </head>

  <body class = "body">
    <%= image_tag 'logo.png', class:"logo" %>
    <%= image_tag '1.png', class:"Btitle" %>
    <%= image_tag '2.png', class:"Btitle" %>
    <%= image_tag '3.png', class:"Btitle" %>
    <%= image_tag '4.png', class:"Btitle" %>
    <br>
    <%= yield %>
    
  </body>
</html>

app/views/quizs/answer.html.erb
<div class = "quiz-block">
<p>
  <strong>タイトル</strong>
  <%= @quiz.title %>
</p>
<h3><strong>
  <% if flash[:notice] %>
    <% if flash[:notice] == "正解です" %>
      <%= image_tag '正解.png', class:"i"%>
    <% end  %>
    <% if flash[:notice] == "不正解です" %>
      <%= image_tag '不正解.png', class:"i"%>
    <% end  %>
  <% end %>
</strong></h3>

<p>
  <strong>回答</strong>
  <%= @ans %>
</p>
<p>
<%= image_tag "/get_image/#{@quiz.id}", class:"i" %>
</p>
<p>
  <strong>問題</strong>
  <%= simple_format(h(@quiz.question)) %>
</p>
<p>
  <strong>答え</strong>
  <%= simple_format(h(@quiz.answer)) %>
</p>
<p>
  <strong>解説</strong>
  <%= simple_format(h(@quiz.comment)) %>
</p>

</div>

<%= link_to 'Back', '/', class:"button"  %>

app/views/quizs/index.html.erb
<p class = "login">
<% if session[:login_uid] %>
  <%= link_to 'ログアウト', top_logout_path, class:"button" %>
<% else %>
  <%= link_to 'ログイン', top_main_path, class:"button" %>
<% end %>
</p>


<br>
<% if session[:login_uid] %>
<p>
  <%= link_to '新規投稿', new_quiz_path, class:"button" %>
</p>
<% end %>

<% if @keyword == nil %>
  <h2>クイズ検索</h2>
  <%= form_tag 'quizs/search', method: :post do %>
    <%= label_tag 'キーワード' %>
    <%= text_field_tag :keyword %>
    <%= submit_tag '検索', class:"button-s"%>
  <% end %>
<% else %>
  <h2>検索結果</h2>
  <%= link_to 'Back', '/', class:"button" %>    
  <% if @quizs == [] %>
    <p><strong><%= @keyword %></strong>
    というキーワードのクイズはありませんでした</p>
  <% end %>
<% end %>

<% @quizs.each do |e| %>
  <p class = "quiz-block">
    
  <font size="5px">
    <%= "タイトル：" %>
    <%= e.title %>
  </font>
  <br>
  <br>
  <%= image_tag "/get_image/#{e.id}", class:"i" %><br>
   

    <br>
    <% if session[:login_uid] %>
        <%= link_to '削除', quiz_path(e), method: :delete, class:"button-1" %>
    <% end %>
    
    <%= link_to '回答', quiz_path(e), class:"button-1" %>
    
  </p>
  

  
<% end %>


<% if @keyword == nil %>
  <%= paginate(@quizs) %>
<% else %>
  <%= link_to 'ホームに戻る', '/', class:"button" %>
<% end %>

app/views/quizs/new.html.erb
<% if @quiz.errors.present? %>
<h3>エラーがあります。</h3>
<ul>
    <% @quiz.errors.full_messages.each do |msg| %>
    <li><%= msg %></li>
    <% end %>
</ul>
<% end %>



<%= form_for @quiz, url: {action: :create} do |f| %>
  <div class = "quiz-block">
    <p>
      <%= f.label :title, 'タイトル' %> <br>
      <%= f.text_area :title, class:"quiz-block-cb" %><br>
    </p>
    <p>
      <%= f.label :question, '問題' %> <br>
      <%= f.text_area :question, class:"quiz-block-cb" %><br>
    </p>
    <p>
      <%= f.label :file, '画像' %>
      <%= f.file_field :file %><br>
    </p>
    <p>
      <%= f.label :answer, '答え' %> <br>
      <%= f.text_area :answer, class:"quiz-block-cb" %><br>
    </p>
    <p>
      <%= f.label :comment, '解説' %> <br>
      <%= f.text_area :comment, class:"quiz-block-cb" %>
    </p>
    <p>
      <%= f.submit '投稿する', class:"button-s" %>
    </p>
  </div>
<% end %>

<%= link_to 'Back', '/', class:"button"  %>

app/views/quizs/show.html.erb
<div class = "quiz-block">
  <p>
    <strong>タイトル</strong>
    <%= @quiz.title %>
  </p>
  <%= image_tag "/get_image/#{@quiz.id}", class:"i" %>
  <p>
    <br>
    <strong>問題</strong>
    <%= simple_format(h(@quiz.question)) %>
  </p>

<%= form_for '/quizs/answer', method: :post do %>
  <%= hidden_field_tag :title, @quiz.title %>
  <%= hidden_field_tag :question, @quiz.question %>
  <%= hidden_field_tag :answer, @quiz.answer %>
  <%= hidden_field_tag :comment, @quiz.comment %>
  <%= label_tag :pans, '回答' %>
  <p class = "quiz-block-cb">
    <%= text_field_tag :pans %>
    <br><br>
    <%= submit_tag '回答する', class:"button-s" %>
  </p>
<% end %> 
<br>
</div>

<%= link_to 'Back', '/', class:"button" %>

app/views/top/login.html.erb
<%= flash[:notice] %>

<%= form_tag top_login_path, method: :post do %>
  <p>
      <%= label_tag :uid, 'ユーザー名：' %> 
      <%= text_field_tag :uid %> 
  </p>
  <p>
      <%= label_tag :pass, 'パスワード：' %> 
      <%= password_field_tag :pass %> 
  </p>

      <%= submit_tag 'ログイン', class:"button-s" %>

<% end %>

<br>
    <%= link_to '新規登録', new_user_path, class:"button" %>
    <%= link_to 'ユーザ一覧', users_path, class:"button" %>
     
    
    <%= link_to '戻る', :back, class:"button" %>

app/views/users/index.html.erb
<%= flash[:notice] %>

<p class = "login">
  <%= link_to 'ログイン', top_main_path, class:"button"  %>
</p>

<br>

<% @users.each do |e| %>
  <p>
    <%= "ユーザー名： " %>
    <%= e.uid %>
    <%= link_to '削除', user_path(e), method: :delete, class:"button"  %>
  </p>
<% end %>

<p>
  <%= link_to '新規登録', new_user_path, class:"button"  %>

  <%= link_to 'ホームに戻る', "/", class:"button" %>
</p>

app/views/users/new.html.erb
<% if @user.errors.present? %>
<h3>エラーがあります。</h3>
<ul>
    <% @user.errors.full_messages.each do |msg| %>
    <li><%= msg %></li>
    <% end %>
</ul>
<% end %>

<%= form_for @user, url: {action: :create} do |f| %>
  <p>
    <%= f.label :uid, 'ユーザー名：' %> 
    <%= f.text_field :uid %> 
  </p>
  <p>
    <%= f.label :pass, 'パスワード：' %> 
    <%= f.password_field :pass %> 
  </p>
  <p>
    <%= f.submit '登録', class:"button-s"  %>
  </p>
  <p>
    <%= link_to '戻る', :back, class:"button"  %>
  </p>
<% end %>